### PR TITLE
Editorial improvements in index.html

### PR DESCRIPTION
**Pull request by riQQ**

### CODE REVIEW

**Comment by Zverik** [comment]
Are you sure about POI → POIs? It doesn't deabbreaviate well: points of interest → ?.

**Comment by riQQ** [comment]
English Wikipedia uses the word POIs multiple times: https://en.wikipedia.org/wiki/Point_of_interest
Another source: https://pro.arcgis.com/en/pro-app/2.7/help/data/indoors/load-points-of-interest.htm

**Comment by Zverik** [comment]
Well the wikipedia page is very inconsistent: for 3 "POIs" there are 9 "POI" in a plural context.

**Comment by riQQ** [comment]
See also https://english.stackexchange.com/questions/55970/plurals-of-acronyms-letters-numbers-use-an-apostrophe-or-not

**Comment by Zverik** [comment]
Okay, why not. Thanks for being persistent!

**Pull request merged**
